version: "3.8"

services:
  cache:
    container_name: "cache"
    restart: unless-stopped
    volumes:
      - cache:/data
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 5

  telegram:
    container_name: "telegram"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/gopray/
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_OWNER_ID=${BOT_OWNER_ID}

      - CACHE_URL=${CACHE_URL}
      - DB_URL=${DB_URL}
      - STORAGE_TYPE=${STORAGE_TYPE}

      - DATA_PATH=${DATA_PATH}
      - LANGUAGES_PATH=${LANGUAGES_PATH}

      - TIME_LOCATION=${TIME_LOCATION}
      - UPCOMING_REMINDER=${UPCOMING_REMINDER}
      - GOMAA_NOTIFY_HOUR=${GOMAA_NOTIFY_HOUR}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      cache:
        condition: service_healthy

  db:
    container_name: "db"
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 2s
      retries: 5

volumes:
  cache:
  db:
