version: "3.8"

services:
  tables-server:
    container_name: "tables-server"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/table/
    environment:
    - TABLE_PATH=${TABLE_PATH}
    - COURSES_PATH=${COURSES_PATH}
    - START_TIME=${START_TIME}
    - PORT=${PORT}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      cache:
        condition: service_healthy