version: "3.8"

services:
  tables-server:
    container_name: "tables-server"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/table/
    environment:
    - START_TIME=${START_TIME}
    - PORT=${PORT}
    - TABLES_URL=${TABLES_URL}
    - TABLES_PSUB=${TABLES_PSUB}
    ports:
      - ${PORT}:${PORT}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development